export const UI_STRINGS = {
  skipToContent: 'Skip to main content',
  navLabel: 'Primary',
  openMenu: 'Open menu',
  closeMenu: 'Close menu',
  menuTitle: 'Navigate',
  switchToLight: 'Switch to light theme',
  switchToDark: 'Switch to dark theme',
  loadingPortfolio: 'Loading portfolio…',
  loadErrorTitle: 'Unable to load portfolio',
  loadErrorBody: 'Please refresh the page or try again in a moment.',
  retry: 'Try again',
  helloPrefix: 'Hi, I’m',
  viewWork: 'My Work',
  downloadResume: 'Resume',
  contactCta: 'Contact',
  aboutEyebrow: 'About',
  featuresEyebrow: 'Features',
  featuresTitle: 'What I Do',
  experienceEyebrow: 'Experience',
  experienceTitle: 'Career journey',
  currentRoleLabel: 'Current role',
  projectsEyebrow: 'Portfolio',
  projectsTitle: 'Featured case studies',
  skillsEyebrow: 'Skillset',
  skillsTitle: 'Tools I use to ship',
  contactEyebrow: 'Contact',
  contactHeadline: 'Hire me',
  contactBody: 'Recruiters and hiring managers are welcome. Email me directly, connect on LinkedIn, or send a note below.',
  emailMeLabel: 'Email me',
  linkedInLabel: 'LinkedIn profile',
  openMailHint: 'Opens your email app',
  formNameLabel: 'Your Name',
  formEmailLabel: 'Your Email',
  formMessageLabel: 'Your Message',
  formSubmit: 'Send Message',
  formSubmitting: 'Sending…',
  formSuccess: 'Thanks — your message was sent.',
  formSuccessLocal: 'Message saved to your inbox. Configure SMTP to also receive email.',
  formError: 'Something went wrong. Please try again.',
  formValidationName: 'Enter at least 2 characters.',
  formValidationEmail: 'Enter a valid email address.',
  formValidationMessage: 'Enter at least 10 characters.',
  fillTestMessage: 'Fill test message',
  openInbox: 'Open message inbox',
  inboxEyebrow: 'Owner tools',
  inboxTitle: 'Message inbox',
  inboxBody: 'Messages from the contact form are stored securely and listed here with your access key.',
  inboxKeyLabel: 'Inbox access key',
  inboxLoad: 'Load messages',
  inboxEmpty: 'No messages yet. Send a test message from the contact form.',
  inboxRefresh: 'Refresh',
  inboxBack: 'Back to site',
  inboxUnauthorized: 'Invalid key. Check MESSAGES_VIEW_KEY in your server .env.',
  inboxEmailOn: 'Email delivery is configured.',
  inboxEmailOff: 'Email delivery is off. Messages are stored locally only.',
  socialNavLabel: 'Social links',
  projectLinksLabel: 'Project links',
  techLabel: 'Tech stack',
  focusAreasLabel: 'Focus areas',
  educationLabel: 'Education',
  certificationsLabel: 'Certifications',
  languagesLabel: 'Languages',
  companiesLabel: 'Companies',
  photoAltSuffix: 'profile portrait',
  recognitionEyebrow: 'Recognition',
  recognitionTitle: 'Certifications & achievements',
  viewCredential: 'View credential',
  viewCertificate: 'View award',
  blogsEyebrow: 'Writing',
  blogsTitle: 'Blogs & articles',
  readArticle: 'Read article',
  footerNote: 'Built for recruiters — public portfolio, no login required.',
};

export const NAV_ITEMS = [
  { id: 'about', label: 'About' },
  { id: 'features', label: 'Services' },
  { id: 'projects', label: 'Portfolio' },
  { id: 'recognition', label: 'Achievements' },
  { id: 'experience', label: 'Experience' },
  { id: 'skills', label: 'Skills' },
  { id: 'blogs', label: 'Blogs' },
  { id: 'contact', label: 'Contact' },
];

export const API_PATHS = {
  portfolio: '/api/portfolio',
  contact: '/api/contact',
  contactMessages: '/api/contact/messages',
  resume: '/api/resume',
};

export const CONTACT_LIMITS = {
  NAME_MIN: 2,
  NAME_MAX: 100,
  MESSAGE_MIN: 10,
  MESSAGE_MAX: 2000,
};

export const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
